name: build
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - name: dependencies
        run: sudo apt-get update && sudo apt install -y libudev-dev libopenal-dev libvorbis-dev libflac-dev libxrandr-dev libfreetype6-dev
      - name: mkdir
        run: mkdir build
      - name: cd
        run: cd build
      - name: cmake
        run: cmake ..
      - name: make
        run: make
