name: build
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Pulling Dependencies
      run: python scripts/install_dep.py
    - name: Performing Initial Setup
      run: python scripts/perform_initial_setup.py
    - name: mkdir
      run: mkdir build
    - name: cd
      run: cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make