name: build
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: dependencies
        run: sudo apt update && sudo apt install -y libudev-dev libopenal-dev libvorbis-dev libflac-dev libxrandr-dev libfreetype6-dev make libopengl-dev
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"
      - name: setup
        run: sudo python3 scripts/perform_initial_setup.py
      - name: mkdir
        run: mkdir -p build
      - name: cmake build
        run: cmake .
      - name: make
        run: make -C build/

